set -g @theme_bg        "#1f1f28"
set -g @theme_surface0  "#2a2a37"
set -g @theme_surface1  "#363646"
set -g @theme_overlay0  "#727169"
set -g @theme_text      "#dcd7ba"

set -g @theme_primary   "#957fb8"
set -g @theme_secondary "#7e9cd8"
set -g @theme_blue      "#7fb4ca"

set -Fg status-style "bg=default,fg=#{@theme_text}"

set -g status-left "#[fg=#{@theme_bg},bg=#{@theme_primary},bold] #S #[fg=#{@theme_primary},bg=#{@theme_bg}] "

set -g status-right "#[fg=#{@theme_blue}]#{?pane_in_mode,COPY ,}#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=#{@theme_overlay0}]#h "

set -g window-status-format "#[fg=#{@theme_overlay0},bg=#{@theme_bg}] #I:#W "

set -g window-status-current-format "#[fg=#{@theme_bg},bg=#{@theme_secondary},bold] #I:#W "

set -Fg pane-border-style "fg=#{@theme_surface1}"
set -Fg pane-active-border-style "fg=#{@theme_primary}"

set -Fg message-style "bg=#{@theme_surface0},fg=#{@theme_text},bold"
set -Fg message-command-style "bg=#{@theme_surface0},fg=#{@theme_blue},bold"

set -Fg mode-style "bg=#{@theme_blue},fg=#{@theme_bg},bold"

setw -Fg clock-mode-colour "#{@theme_primary}"
